// Code generated by Slice Machine. DO NOT EDIT.

import TechSlice from './TechSlice';
import TextSlice from './TextSlice';
import TriImageSlice from './TriImageSlice';

export {
	TechSlice,
	TextSlice,
	TriImageSlice,
};

export const components = {
	tech_slice: TechSlice,
	text_slice: TextSlice,
	tri_image_slice: TriImageSlice,
};
