// Code generated by Slice Machine. DO NOT EDIT.

import DualImageSlice from './DualImageSlice';
import TechSlice from './TechSlice';
import TextSlice from './TextSlice';
import TriImageSlice from './TriImageSlice';
import WorkProjectSlice from './WorkProjectSlice';

export {
	DualImageSlice,
	TechSlice,
	TextSlice,
	TriImageSlice,
	WorkProjectSlice,
};

export const components = {
	dual_image_slice: DualImageSlice,
	tech_slice: TechSlice,
	text_slice: TextSlice,
	tri_image_slice: TriImageSlice,
	work_project_slice: WorkProjectSlice,
};
