// Code generated by Slice Machine. DO NOT EDIT.

import BlogSingleImage from './BlogSingleImage';
import BlogTextContent from './BlogTextContent';
import DualImageSlice from './DualImageSlice';
import TechSlice from './TechSlice';
import TextSlice from './TextSlice';
import TriImageSlice from './TriImageSlice';
import WorkProjectSlice from './WorkProjectSlice';

export {
	BlogSingleImage,
	BlogTextContent,
	DualImageSlice,
	TechSlice,
	TextSlice,
	TriImageSlice,
	WorkProjectSlice,
};

export const components = {
	blog_single_image: BlogSingleImage,
	blog_text_content: BlogTextContent,
	dual_image_slice: DualImageSlice,
	tech_slice: TechSlice,
	text_slice: TextSlice,
	tri_image_slice: TriImageSlice,
	work_project_slice: WorkProjectSlice,
};
